// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://srmmypfbxvzzpparoqig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybW15cGZieHZ6enBwYXJvcWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3ODQyNTMsImV4cCI6MjA4NjM2MDI1M30.CSxlQ32evdovmjCkuQpfYHKqnZKHwkdb45K7oe7QRFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);